apiVersion: v1
kind: ServiceAccount
metadata:
  name: apiaks-metrics-reader
  namespace: apiaks
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: metrics-reader
rules:
  # métricas del metrics-server
  - apiGroups: ["metrics.k8s.io"]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]

  # información del nodo (CPU capacity, Memory capacity)
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]

  # acceso a subrecursos del nodo (necesario para CPU usada)
  - apiGroups: [""]
    resources: ["nodes/proxy", "nodes/stats", "nodes/metrics"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: apiaks-metrics-reader-binding
subjects:
  - kind: ServiceAccount
    name: apiaks-metrics-reader
    namespace: apiaks
roleRef:
  kind: ClusterRole
  name: metrics-reader
  apiGroup: rbac.authorization.k8s.io
