apiVersion: v1
kind: ServiceAccount
metadata:
  name: apiaks-metrics-reader
  namespace: apiaks
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: metrics-reader
rules:
  - apiGroups: ["metrics.k8s.io"]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: apiaks-metrics-reader-binding
subjects:
  - kind: ServiceAccount
    name: apiaks-metrics-reader
    namespace: apiaks
roleRef:
  kind: ClusterRole
  name: metrics-reader
  apiGroup: rbac.authorization.k8s.io
